name: api-gateway

on:
  push:
    branches: [ master ]
    paths:
      - 'infrastructure/api-gateway/**'
  workflow_dispatch:

jobs:
  package-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.1.7"

      - name: Initialize Terraform
        run: terraform init
        working-directory: ./infrastructure/api-gateway

      - name: Deploy with Terraform
        run: terraform apply -auto-approve
        working-directory: ./infrastructure/api-gateway
