name: api-summoner

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'api/summoner/**'
      - 'shared/**'
  push:
    branches: [ master ]
    paths:
      - 'api/summoner/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  lambda-workflow:
    uses: ./.github/workflows/lambda-workflow.yaml
    with:
      service-path: './api/summoner'
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: us-east-1
