name: api-summoner

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'api/summoner/**'
      - 'shared/**'
  push:
    branches: [ master ]
    paths:
      - 'api/summoner/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  lambda-workflow:
    permissions:
      id-token: write
      contents: read
    uses: ./.github/workflows/lambda-workflow.yaml
    with:
      service_path: './api/summoner'