name: api-summoner

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'api/summoner/**'
      - 'shared/**'
  push:
    branches: [ master ]
    paths:
      - 'api/summoner/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  lambda-workflow:
    uses: ./.github/workflows/lambda-workflow.yaml@master
    with:
      service_path: './api/summoner'