name: name-updater-producer

on:
  pull_request:
    branches: [ master ]
    paths:
      - 'name-updater/producer/**'
      - 'shared/**'
  push:
    branches: [ master ]
    paths:
      - 'name-updater/producer/**'
      - 'shared/**'
  workflow_dispatch:

jobs:
  lambda-workflow:
    uses: ./.github/workflows/lambda-workflow.yaml
    with:
      service-path: './name-updater/producer'
      aws-region: 'us-east-1'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
